Repository TechnologyWithoutBorders/Swift-Web, pull requests merged in 2022-02, with the labels that each got.

#38 Feature/create reports
  lib/screens/technicians/technicianDeviceScreen.dart
  lib/utilities/dataAction.dart
  lib/utilities/networkFunctions.dart
Labels: enhancement

#40 Refresh on resume
  lib/screens/technicians/dashboardScreen.dart
  lib/screens/technicians/inventoryScreen.dart
Labels: usability

#41 Fix login screen scaling
  lib/main.dart
Labels: bug

#42 sort user list
  lib/screens/technicians/userManagementScreen.dart
Labels: usability

#47 User selection
  lib/screens/technicians/tabScreen.dart
  lib/screens/technicians/technicianDeviceScreen.dart
  lib/utilities/constants.dart
  lib/utilities/networkFunctions.dart
  lib/utilities/preferenceManager.dart
Labels: usability

#45 revamp inventory filtering
  lib/screens/technicians/inventoryScreen.dart
Labels: usability

#49 implement user creation as dialog
  lib/screens/technicians/userManagementScreen.dart
Labels: usability

#56 fix user change
  lib/screens/technicians/tabScreen.dart
Labels: bug

#57 Organization filter dialog
  lib/screens/organizationFilterView.dart
  lib/screens/overviewScreen.dart
  lib/screens/technicians/inventoryScreen.dart
Labels: enhancement

#59 Assign devices to org units
  lib/screens/deviceInfoScreen.dart
  lib/screens/overviewScreen.dart
  lib/screens/technicians/dashboardScreen.dart
  lib/screens/technicians/inventoryScreen.dart
  lib/screens/technicians/technicianDeviceScreen.dart
  lib/utilities/hospitalDevice.dart
Labels: usability

#50 check for Hospital Preferences in Login
  lib/main.dart
  lib/screens/overviewScreen.dart
  lib/screens/technicians/tabScreen.dart
  lib/utilities/preferenceManager.dart
Labels: maintenance

#61 wrap layout in flexibles
  lib/screens/overviewScreen.dart
Labels: usability

#66 Revamp app bar
  lib/main.dart
  lib/screens/overviewScreen.dart
  lib/screens/technicians/dashboardScreen.dart
  lib/screens/technicians/tabScreen.dart
  lib/utilities/constants.dart
  lib/utilities/preferenceManager.dart
  pubspec.lock
Labels: usability

#68 Rearrange people screen
  lib/main.dart
  lib/screens/overviewScreen.dart
  lib/screens/technicians/tabScreen.dart
  lib/screens/technicians/userManagementScreen.dart
  lib/utilities/constants.dart
  lib/utilities/preferenceManager.dart
Labels: usability

#70 Show devices up for maintenance
  lib/main.dart
  lib/screens/technicians/dashboardScreen.dart
  lib/utilities/constants.dart
  lib/utilities/dataAction.dart
  lib/utilities/deviceStats.dart
  lib/utilities/networkFunctions.dart
Labels: bug, maintenance

#71 Organization filter dialog
  lib/screens/organizationFilterView.dart
  lib/screens/technicians/inventoryScreen.dart
Labels: enhancement

#72 Report dialog
  lib/screens/deviceInfoScreen.dart
Labels: usability

#73 Organization filter dialog
  lib/screens/deviceInfoScreen.dart
  lib/screens/overviewScreen.dart
  lib/utilities/networkFunctions.dart
Labels: enhancement

#75 Edit organisation units
  lib/screens/technicians/organizationScreen.dart
Labels: usability

#76 Animate filtering
  lib/screens/overviewScreen.dart
Labels: usability

#77 Assign devices to departments
  lib/screens/technicians/organizationScreen.dart
  lib/utilities/hospitalDevice.dart
  lib/utilities/networkFunctions.dart
  lib/utilities/organizationalRelation.dart
  lib/utilities/organizationalUnit.dart
Labels: enhancement
