Repository TechnologyWithoutBorders/Swift-Web, pull requests merged in 2022-01, with the labels that each got.

#10 use subtype of exception in order to provide message
  lib/main.dart
  lib/utilities/messageException.dart
  lib/utilities/networkFunctions.dart
Labels: bug

#11 Organizational units
  lib/screens/technicians/organizationScreen.dart
  lib/screens/technicians/tabScreen.dart
  lib/screens/technicians/userManagementScreen.dart
  lib/utilities/dataAction.dart
  lib/utilities/networkFunctions.dart
  lib/utilities/organizationalRelation.dart
  lib/utilities/organizationalUnit.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#14 Adapt filter buttons
  lib/screens/technicians/inventoryScreen.dart
Labels: text

#17 Feature/show device infos
  lib/screens/technicians/dashboardScreen.dart
  lib/screens/technicians/inventoryScreen.dart
  lib/screens/technicians/technicianDeviceScreen.dart
  lib/utilities/hospital.dart
  lib/utilities/hospitalDevice.dart
  lib/utilities/networkFunctions.dart
Labels: enhancement

#18 Feature/show device infos
  lib/screens/technicians/technicianDeviceScreen.dart
  lib/utilities/detailedReport.dart
  lib/utilities/deviceInfo.dart
  lib/utilities/networkFunctions.dart
Labels: enhancement

#19 fix type error
  lib/utilities/user.dart
Labels: enhancement

#25 Organizational units
  lib/screens/technicians/organizationScreen.dart
  lib/utilities/dataAction.dart
  lib/utilities/networkFunctions.dart
  lib/utilities/organizationalRelation.dart
  lib/utilities/organizationalUnit.dart
Labels: enhancement

#33 revamp login screen
  lib/main.dart
Labels: usability

#34 Fix login problem
  lib/main.dart
Labels: bug
